// src/lib/components/Attribute.svelte
<script lang="ts">
	import { IconCopy } from "@tabler/icons-svelte";
	import { toast } from "@zerodevx/svelte-toast";
	import clsx from "clsx";
	export let key: string;
	export let value: string;
	export let copyable = false;
</script>

<dl class="flex gap-1 text-sm">
	<dt
		class="w-1/4 shrink-0 min-w-0 truncate text-gray-700 dark:text-gray-300"
	>
		{key}
	</dt>
	{#if copyable}
		<button
			class="focus:outline-none flex items-center gap-x-1 truncate hover:bg-zinc-100 dark:hover:bg-zinc-800 rounded-md"
			on:click={() => {
				navigator.clipboard.writeText(value);
				toast.push("Copied " + key);
			}}
		>
			<dd class="min-w-0 truncate px-2 py-1">
				{value}
			</dd>
			<IconCopy
				stroke={1}
				size={24}
				class="text-gray-600 dark:text-gray-200 pr-2"
			/>
		</button>
	{:else}
		<dd class="min-w-0 truncate px-2 py-1">
			{value}
		</dd>
	{/if}
</dl>

// app/components/attribute.tsx
import { Check, Copy, Info } from "lucide-react";

import cn from "~/utils/cn";
import toast from "~/utils/toast";

import Tooltip from "./tooltip";

export interface AttributeProps {
  name: string;
  value: string;
  tooltip?: string;
  isCopyable?: boolean;
}

export default function Attribute({ name, value, tooltip, isCopyable }: AttributeProps) {
  return (
    <dl className="flex items-center gap-1 text-sm">
      <dt
        className={cn(
          "w-1/3 sm:w-1/4 lg:w-1/3 shrink-0 min-w-0",
          "text-mist-500 dark:text-mist-400",
          tooltip ? "flex items-center gap-1" : undefined,
        )}
      >
        {name}
        {tooltip ? (
          <Tooltip>
            <Info className="size-4" />
            <Tooltip.Body>{tooltip}</Tooltip.Body>
          </Tooltip>
        ) : undefined}
      </dt>
      <dd
        className={cn(
          "min-w-0 px-1.5 py-1 rounded-lg border border-transparent",
          ...(isCopyable
            ? [
                "cursor-pointer hover:shadow-xs",
                "hover:bg-mist-50 dark:hover:bg-mist-800",
                "hover:border-mist-100 dark:hover:border-mist-700",
              ]
            : []),
        )}
      >
        {isCopyable ? (
          <button
            type="button"
            className="relative flex w-full min-w-0 items-center gap-1.5"
            onClick={async (event) => {
              const svgs = event.currentTarget.querySelectorAll("svg");
              for (const svg of svgs) {
                svg.toggleAttribute("data-copied", true);
              }

              await navigator.clipboard.writeText(value);
              toast(`Copied ${name} to clipboard`);

              setTimeout(() => {
                for (const svg of svgs) {
                  svg.toggleAttribute("data-copied", false);
                }
              }, 1000);
            }}
          >
            <div suppressHydrationWarning className="truncate">
              {value}
            </div>
            {isCopyable ? (
              <div>
                <Check className="hidden size-4 data-copied:block" />
                <Copy className="block size-4 data-copied:hidden" />
              </div>
            ) : undefined}
          </button>
        ) : (
          <div className="relative min-w-0 truncate" suppressHydrationWarning>
            {value}
          </div>
        )}
      </dd>
    </dl>
  );
}
